apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cronjob.name" . }}
  labels:
    app: {{ template "cronjob.name" . }}
    chart: {{ template "cronjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrency }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "cronjob.name" . }}
            release: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: [{{- range $index, $element := .Values.image.command}}
                          {{- if $index}},{{- end}}
                          {{- $element | quote}}
                        {{- end}}]
              # Inject (non sensitive) environment variables from the `Values` config.
              env:
              {{- range $key, $val := .Values.nonSensitiveEnvs }}
              - name: {{ $key }}
                value: {{ $val | quote }}
              {{- end}}
              # Inject (sensitive) environment variables from `Values` config, referring
              # them from the related Secret object. This is an extra measure of security
              # to avoid having credentials displayed in plain text in the template file.
              # https://kubernetes.io/docs/concepts/configuration/secret/
              {{- $chartName := include "cronjob.name" . -}}
              {{- range $key, $val := .Values.sensitiveEnvs }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $chartName }}-secret
                    key: {{ $key }}
              {{- end}}
              resources:
{{ toYaml .Values.resources | indent 16 }}
