{{- if .Values.externalConfig.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cronjob.fullname" . }}-external-config-secret
  labels:
    app: {{ template "cronjob.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  config.json: |
    {{ .Values.externalConfig.content | b64enc }}
{{- end -}}