apiVersion: v1
description: Helm chart for deploying an instance of logentries as a DaemonSet on all nodes of a K8s cluster.
name: logentries
version: 1.0.0
appVersion: 0.2.0
maintainers:
  - name: heshamMassoud