apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.name }}-htpasswd-secret
  labels:
    app: {{ template "public-service.name" . }}
    chart: {{ template "public-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  htpasswd: {{ .Values.nginx.basicAuth.htpasswd | b64enc }}