{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.name }}-config
  labels:
    app: {{ template "public-service.name" . }}
    chart: {{ template "public-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |
    events {}
    http {


     server {
        listen {{ .Values.nginx.port }};
        location = /healthz {
         gzip off;
         auth_basic off;
         # skip flooding logs of the health-check
         access_log off;
         #return http-status 200
         return 200 "nginx for service  {{ template "public-service.fullname" . }} is healthy\n";
    }

       location / {
         auth_basic "Protected Area";
         auth_basic_user_file /etc/nginx/.htpasswd;
         proxy_pass http://127.0.0.1:{{ .Values.containerPort }};  # Forward to your application
       }
     }
    }
{{- end }}
