{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.name }}-config
  labels:
    app: {{ template "public-service.name" . }}
    chart: {{ template "public-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |
    events {}
    http {
     server {
       listen {{ .Values.nginx.port }};
       location / {
         auth_basic "Protected Area";
         auth_basic_user_file /etc/nginx/.htpasswd;
         proxy_pass http://127.0.0.1:{{ .Values.containerPort }};  # Forward to your application
       }
     }
    }
{{- end }}
