apiVersion: v1
kind: Service
metadata:
  name: {{ template "public-service.fullname" . }}
  labels:
    app: {{ template "public-service.name" . }}
    chart: {{ template "public-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "public-service.name" . }}
    release: {{ .Release.Name }}
  ports:
    targetPort: {{ .Values.service.internalPort }}
  - port: {{ .Values.service.port }}
    protocol: TCP
