userData: ""

sshConfig:
  ssh_host_ed25519_key: ""
  ssh_host_ed25519_key_pub: ""
  ssh_host_rsa_key: ""
  ssh_host_rsa_key_pub: ""

service:
  port: 22
  nodePort: 31000

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  existingClaim: ""
  size: 20Gi
  # storageClass: "-"
  subPath: ""