apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "logentries.fullname" . }}
  labels:
      app: {{ template "logentries.name" . }}
      chart: {{ template "logentries.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "logentries.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "logentries.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        args:
          - "-t $LOGENTRIES_TOKEN"
        {{- range $val := .Values.args }}
          - {{ $val | quote }}
        {{- end}}
        volumeMounts:
        - name: socket
          mountPath: /var/run/docker.sock
        env:
        - name: LOGENTRIES_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "logentries.name" . }}-secret
              key: logentries_token
      volumes:
        - name: socket
          hostPath:
            path: /var/run/docker.sock