## The secret resource is required in order to hide secrets within the K8s UI. If we skip the usage of secrets yaml,
## sensitive information would be shown in plain text i.e. in the Google console.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logentries.name" . }}-secret
  labels:
    app: {{ template "logentries.name" . }}
    chart: {{ template "logentries.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  logentries_token: {{ .Values.logentriesToken | b64enc }}