image:
  repository: ''  # either 'sphereio/commercetools-payone-integration' or 'commercetoolsps/commercetools-paypal-plus-integration/'
  tag: ''  # set tag here
  pullPolicy: IfNotPresent

containerName: payment-integration

service:
  type: NodePort
  externalPort: 80
  internalPort: 8080

rollingUpdateStrategy:
  maxSurge: 1
  maxUnavailable: 0

portName: backend-port

resources:
#  requests:
#    cpu: 100m
#    memory: 300Mi
#  limits:
#    cpu: 100m
#    memory: 400Mi

ingress:
  annotations: ''
