image:
  name: ''
  repository: ''
  tag: ''
  pullPolicy: 'ifNotPresent'

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
#  requests:
#    cpu: 50m
#    memory: 256Mi
#  limits:
#    cpu: 150m
#    memory: 512Mi

schedule: '*/1 * * * *'

# non sensitive environment variables
nonSensitiveEnvs: {}

# sensitive environment variables
sensitiveEnvs: {}