nonSensitiveEnvs:
#  TENANTS: 'TENANT_NAME'
#  TENANT_NAME_UPDATE_ORDER_PAYMENT_STATE: 'true'
#  TENANT_NAME_PAYONE_MODE: 'test'

ingress:
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.allow-http: 'false'
#     kubernetes.io/ingress.global-static-ip-name: '<<SET_IN_PROJECT>>'
#     ingress.gcp.kubernetes.io/pre-shared-cert: '<<SET_IN_PROJECT>>'
