apiVersion: v1
kind: Service
metadata:
  name: {{ template "payment.fullname" . }}
    labels:
      app: {{ template "payment.name" . }}
      chart: {{ template "payment.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
