## The secret resource is required in order to hide secrets within the K8s UI. If we skip the usage of secrets yaml,
## sensitive information would be shown in plain text i.e. in the Google console.
apiVersion: v1
kind: Secret
metadata:
  # The identifier of this Secret, unique within a namespace.
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Inject (sensitive) environment variables from `Values` config.
  {{- range $key, $val := .Values.sensitiveEnvs }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
