## sensitive environment variables
sensitiveEnvs: {}

service:
  port: 80
## Ingress annotations
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: '/*'
  hosts:
    - 'service-name.local'
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nginx:
  enabled: false
  name: nginx
  port: 8080
## specifies the configuration for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  httpGet:
    path: '/health'
    port: 'container-port'
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: '/health'
    port: 'container-port'
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## enable/disable affinity rules for k8 component scheduling
affinity:
  enabled: false

## Pod Disruption Budget definition
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
pdb:
  enabled: false
  spec:
    maxUnavailable: "10%"

# Google managed certificates for publicly exposed services
managecertificate:
  enabled: false