image:
  repository: 'MUST_BE_OVERRIDDEN'  # either 'sphereio/commercetools-payone-integration' or 'commercetoolsps/commercetools-paypal-plus-integration/'
  tag: 'MUST_BE_OVERRIDDEN'  # set tag here
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

rollingUpdateStrategy:
  maxSurge: 1
  maxUnavailable: 0

portName: backend-port

## specifies the resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
#  requests:
#    cpu: 100m
#    memory: 300Mi
#  limits:
#    cpu: 100m
#    memory: 400Mi

# non sensitive environment variables
nonSensitiveEnvs: {}

# sensitive environment variables
sensitiveEnvs: {}

## Ingress annotations
##
ingress:
  annotations: {}
    # kubernetes.io/ingress.class: "nginx"
    # secretName: my-tls-cert
    # kubernetes.io/tls-acme: "true"
