apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sftp-service.fullname" . }}-host-key
  labels:
    app: {{ template "sftp-service.name" . }}
    chart: {{ template "sftp-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ssh_host_ed25519_key: {{ .Values.sshConfig.ssh_host_ed25519_key | b64enc }}
  ssh_host_rsa_key: {{ .Values.sshConfig.ssh_host_rsa_key | b64enc }}
  ssh_host_ed25519_key_pub: {{ .Values.sshConfig.ssh_host_ed25519_key_pub  | b64enc}}
  ssh_host_rsa_key_pub: {{ .Values.sshConfig.ssh_host_rsa_key_pub | b64enc }}
type: Opaque