apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.image.name }}
            appVersion: {{ .Values.image.tag }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: {{ .Values.image.name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              # Inject (non sensitive) environment variables from the `Values` config.
              env:
              {{- range $key, $val := .Values.nonSensitiveEnvs }}
              - name: {{ $key }}
                value: {{ $val | quote }}
              {{- end}}
              # Inject (sensitive) environment variables from `Values` config, referring
              # them from the related Secret object. This is an extra measure of security
              # to avoid having credentials displayed in plain text in the template file.
              # https://kubernetes.io/docs/concepts/configuration/secret/
              {{- $chartName := .Chart.Name -}}
              {{- range $key, $val := .Values.sensitiveEnvs }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $chartName }}-secret
                    key: {{ $key }}
              {{- end}}
              resources:
{{ toYaml .Values.resources | indent 16 }}
