## The secret resource is required in order to hide secrets within the K8s UI. If we skip the usage of secrets yaml,
## sensitive information would be shown in plain text i.e. in the Google console.
apiVersion: v1
kind: Secret
metadata:
  # The identifier of this Secret, unique within a namespace.
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  logentries_token: {{ .Values.logentriesToken | b64enc }}


